name: Conan 2 CI

on:
  push:
    branches:
      - master

jobs:
  conan_build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y python3-pip

    - name: Install Conan
      run: sudo pip3 install conan

    - name: Detect profile
      run: conan profile detect

    - name: Build and test package
      run: |
        conan create . -s build_type=Debug -s compiler.cppstd=17 --build missing --version 4.0.2