name: Conan 2 CI

on:
  push:
    branches:
      - master

jobs:
  conan_build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Restore Conan cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.conan
          ~/.conan2
        key: conan-cache-${{ runner.os }}
        restore-keys: conan-cache-${{ runner.os }}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y python3-pip

    - name: Install Conan
      run: sudo pip3 install conan==1.59.0

    - name: Detect profile
      run: conan profile detect

    - name: Build and test package v3.5.6
      run: conan create . 3.5.6@ -s build_type=Debug -s compiler.cppstd=17 --build missing
      
    - name: Build and test package v3.7.0
      run: conan create . 3.7.0@ -s build_type=Debug -s compiler.cppstd=17 --build missing
      
    - name: Build and test package v3.8.3
      run: conan create . 3.8.3@ -s build_type=Debug -s compiler.cppstd=17 --build missing
      
    - name: Build and test package v4.0.1
      run: conan create . 4.0.1@ -s build_type=Debug -s compiler.cppstd=17 --build missing
      
    - name: Build and test package v4.0.2
      run: conan create . 4.0.2@ -s build_type=Debug -s compiler.cppstd=17 --build missing
      
    - name: Build and test package v4.1.1
      run: conan create . 4.1.1@ -s build_type=Debug -s compiler.cppstd=17 --build missing


    - name: Save Conan cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.conan
          ~/.conan2
        key: conan-cache-${{ runner.os }}
        restore-keys: conan-cache-${{ runner.os }}